### ISSUE TITLE
看不到共享盒子邻居数量

### ISSUE THREAD

**Issue by shangji666** [Aniverse/A#3]
这个应该如何操作

**Comment by Aniverse** [comment]
emmm 你就不能多提供点信息么？有些共享盒子区别很大的，至少你得说你用的是哪家，以及哪个 plan 吧？
最好能把脚本运行的截图发上来

**Comment by shangji666** [comment]
![image](https://user-images.githubusercontent.com/56227371/94982097-6b4fdb80-056a-11eb-86e3-116fff3c5db1.png)
云筏
![image](https://user-images.githubusercontent.com/56227371/94982108-84f12300-056a-11eb-8782-1da361c2bdf8.png)
腾讯
是只有pt盒子才能看到邻居数量吗

**Comment by Aniverse** [comment]
**KVM 的 VPS 不会被认为是共享盒子，尽管它的资源确实是共享的**
一般我们说的共享盒子是指没有任何虚拟化架构（Docker 不算）的情况下，多个用户使用同一台机器
比如 FeralHosting、SeedHost、Dediseedbox、Seedboxco 都属于这类情况

RapidSeedbox 这类基于 OpenVZ 的 VPS Seedbox 一般也不当做共享盒子处理
